### ISSUE TITLE
Incorrect plugin version match

### ISSUE THREAD

**Issue by noahgibbs** [jtimberman/vagrant-cookbook#20]
Currently the cookbook returns the same version for all plugins installed. This means that if you specify plugin versions for several different plugins, they get repeatedly reinstalled because the version doesn't match the very first plugin for all of them.

That's because of this code, from providers/plugin.rb:

    def load_current_resource
      @current_resource = Chef::Resource::VagrantPlugin.new(new_resource)
      vp = shell_out("vagrant plugin list")
      if vp.stdout.include?(new_resource.plugin_name)
        @current_resource.installed(true)
        @current_resource.installed_version(vp.stdout.split[1].gsub(/[\(\)]/, ''))
      end
      @current_resource
    end

See how the installed_version line with the regexp doesn't depend on which plugin name is being queried? The cookbook will probably need to actually parse the output. Here's example output with constraints, as sample input:

    Athanor:madscience_gem noah$ vagrant plugin list
    vagrant-aws (0.6.0)
    vagrant-digitalocean (0.7.3)
      - Version Constraint: 0.7.3
    vagrant-host-shell (0.0.4)
      - Version Constraint: 0.0.4
    vagrant-librarian-chef (0.2.1)
      - Version Constraint: 0.2.1
    vagrant-linode (0.1.1)
      - Version Constraint: 0.1.1
    vagrant-omnibus (1.4.1)
      - Version Constraint: 1.4.1
    vagrant-share (1.1.4, system)

This is annoying me right now, so maybe I'll make a pull request happen for this.

**Comment by jtimberman** [comment]
#21 was merged.
