### ISSUE TITLE
Debian box seems not to work for Test Kitchen

### ISSUE THREAD

**Issue by noahgibbs** [jtimberman/vagrant-cookbook#24]
My dev box can't seem to find the debian-7.6 box it says it needs. It *can* find debian-ubuntu-1404, so I don't think it's just "doesn't work." OS X also doesn't work, but TESTING.md mentions that it needs a custom box, so that's expected.

(And yeah, I installed everything mentioned in TESTING.md.)

Thanks!

**Comment by noahgibbs** [comment]
Although it looks like the Ubuntu test kitchen setup doesn't complete right either. It's failing when trying to grab dpgk-dev:

```
       E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/d/dpkg/dpkg-dev_1.17.5ubuntu5.3_all.deb  404  Not Found [IP: 91.189.91.23 80]

       E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
       ---- End output of apt-get -q -y install build-essential=11.6ubuntu6 ----
       Ran apt-get -q -y install build-essential=11.6ubuntu6 returned 100
       [2015-04-11T22:07:15+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
>>>>>> Converge failed on instance <debian-ubuntu-1404>.
>>>>>> Please see .kitchen/logs/debian-ubuntu-1404.log for more details
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: SSH exited (1) for command: [sh -c '
sudo -E /opt/chef/bin/chef-client --local-mode --config /tmp/kitchen/client.rb --log_level auto --force-formatter --no-color --chef-zero-port 8889 --json-attributes /tmp/kitchen/dna.json
']
>>>>>> ----------------------
```

**Comment by till** [comment]
@noahgibbs I could be wrong, but usually, that means the apt-cache is stale and you need to `apt-get update`. We often run that with a provisioner before the actual bootstrapping starts.

**Comment by noahgibbs** [comment]
@till Entirely possible. I didn't do a lot of futzing to get it to work. I basically checked, "works out of box? No."

**Comment by jtimberman** [comment]
In #28, I've removed the Debian box. I've also added apt-get update to the top of the test recipe, and include the build-essential and vagrant recipes from that.

That should resolve this issue.

Cheers,
Joshua
