### ISSUE TITLE
install plugins for users

### ISSUE THREAD

**Issue by till** [jtimberman/vagrant-cookbook#27]
I am trying to install plugins for a specific user (backstory, deploying this to a box to run CI on vagrant setups). So I noticed this isn't possible currently, but I was more interested if you'd like a PR for that.

Sort of related — was wondering why you shellout vs. using an `execute` resource for most of the things. Any thoughts on that? These would probably allow me to easily run something as a user and I wouldn't have to rely on sudo or su hacks which may not work on Windows anyway.

**Comment by miguelaferreira** [comment]
Installing plugins for a specific user has been merged in commit ec05ddc1d7fc2fcc70fc9111f397d90ee56a38f3

I've been using it an it works, although you can't install plugins for multiple users. If you want to do that you could wrap the cookbook in different recipes, or dynamically change the attribute that sets the user and call the respective recipe again.

**Comment by till** [comment]
@miguelaferreira Awesome, doesn't seem to be released though? I'll close this regardless.

**Comment by miguelaferreira** [comment]
No it hasn't. I've actually opened an issue (#26) asking for a new release because of that. Feel free to express you support :+1:
