### ISSUE TITLE
NoMethodError: undefined method `installed_version=' for LWRP resource vagrant_plugin from cookbook vagrant

### ISSUE THREAD

**Issue by promisedlandt** [jtimberman/vagrant-cookbook#32]
Hi,

I get the error
`NoMethodError: undefined method `installed_version=' for LWRP resource vagrant_plugin from cookbook vagrant`
after updating the cookbook.
Offending line is this:
https://github.com/jtimberman/vagrant-cookbook/blob/master/providers/plugin.rb#L16

If I comment it out, it works. Unfortunately, I don't understand what the line was meant to do in the first place. In previous versions, it appears to be a variable that isn't used anywhere, and in the current version it looks like it gets overwritten in the next line.

Problem appears to be from this commit: https://github.com/jtimberman/vagrant-cookbook/commit/cbecfaa9f0703aecb5e7ee3fa2a125b554cea9e0

**Comment by noahgibbs** [comment]
Looks like some kind of merge error between a commit of @jtimberman and a commit of mine.

**Comment by miguelaferreira** [comment]
I'm seeing the same issue in version 0.3.1

**Comment by tya** [comment]
+1
