### ISSUE TITLE
Compile error when bintray is unavailable.

### ISSUE THREAD

**Issue by bignastybryce** [jtimberman/vagrant-cookbook#37]
If chef is not able to retrieve the vagrant checksum from bintray, it results in a compile error for any node that has the vagrant cookbook in its dependencies (when the helper method tries to fetch the checksum in the attributes file).  I expect this would happen even if the URL and checksum attributes were set elsewhere (I haven't tested that).  Today's bintray issue manifested this behavior on my nodes.

Would it be acceptable to rescue these errors and set the default attributes to nil in that case?  This should only make nodes that actually need to perform an install be broken if bintray is not working, and none at all if the attributes are set elsewhere.

I was about to start working on that when bintray came back.  I could still do it - or maybe someone else has a better idea?

**Comment by dougireton** [comment]
You also see this issue when running specs without an Internet connection.
Specs should not be dependent on any outside resources.

Rescuing and returning nil seems reasonable to me. You would either
re-downlad the package or the ackage download would would fail altogether.

On Tuesday, September 22, 2015, Bryce Lynn <notifications@github.com> wrote:

> If chef is not able to retrieve the vagrant checksum from bintray, it
> results in a compile error for any node that has the vagrant cookbook in
> its dependencies (when the helper method tries to fetch the checksum in the
> attributes file). I expect this would happen even if the URL and checksum
> attributes were set elsewhere (I haven't tested that). Today's bintray
> issue manifested this behavior on my nodes.
>
> Would it be acceptable to rescue these errors and set the default
> attributes to nil in that case? This should only make nodes that actually
> need to perform an install be broken if bintray is not working, and none at
> all if the attributes are set elsewhere.
>
> I was about to start working on that when bintray came back. I could still
> do it - or maybe someone else has a better idea?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jtimberman/vagrant-cookbook/issues/37>.
>


-- 

Thanks,

Doug Ireton
