### ISSUE TITLE
Dependency on windows ~> 1.38 preventing use with later windows versions

### ISSUE THREAD

**Issue by ryangribble** [jtimberman/vagrant-cookbook#67]
Hi guys

I was trying to use this community cookbook to install vagrant on windows, but some other cookbooks we are writing are using a later `windows` cookbook version (2.1.1)

This vagrant cookbook is pessimistically locked to windows 1.38.x and thus the dependencies cant be satisfied.

Im still getting up to speed with chef concepts, so am not sure of the reasons why or why not to pessimistically lock the versions like this, but it seems unless there is some hard dependency where this cookbook wont work with windows above 1.38 that using the pessimistic verisoning like this is really just preventing potential consumers from succesfully pulling it in?

Would "the fix" in this case be to just change this cookbook to use `>= 1.38` rather than `~> 1.38` ?

**Comment by phwelo** [comment]
same issue here. berks output:
```
Fetching cookbook index from https://supermarket.chef.io...
Unable to satisfy the following requirements:

- `windows (= 2.1.1)` required by `user-specified dependency`
- `windows (~> 1.38)` required by `vagrant-0.6.0`
- `windows (>= 1.36.1)` required by `ms_dotnet-3.1.0`
- `windows (>= 1.44.0)` required by `powershell-5.1.0`
```

**Comment by ryangribble** [comment]
I see a PR was actually sent for this prior to me raising the issue #66 but it is not yet merged...
