### ISSUE TITLE
Unable to specify vagrant version when using a wrapper cookbook

### ISSUE THREAD

**Issue by rich-murray** [jtimberman/vagrant-cookbook#76]
Hi I'm having trouble specifying the Vagrant version (and plugin's to install) when using a wrapper cookbook.  The vagrant version is always defaulting to 1.9.7.

In my wrapper cookbook I include the the vagrant recipe as follows:
``
include_recipe 'vagrant'
``

I'm using Berkshelf so have a dependency on the vagrant cookbook in a Berksfile.

In my wrapper cookbook I've tried setting the following attributes (in the file attributes/default.rb)

```
default['vagrant']['version'] = '2.0.1'
default['vagrant']['url'] = 'http://{mylocalserver}/vagrant_2.0.1_x86_64.deb'
default['vagrant']['checksum'] = '2f9498a83b3d650fcfcfe0ec7971070fcd3803fad6470cf7da871caf2564d84f'
default['vagrant']['user'] = node['bpm']['user']
default['vagrant']['plugins'] = [
   {
     'name' => 'vagrant-berkshelf',
     'version' => '5.1.2'
   }, {
     'name' => 'vagrant-omnibus',
     'version' => '1.5.0'
   }, {
     'name' => 'vagrant-cachier',
     'version' => '1.2.1'
   }]
```

When I run Chef solo (13.6.4.) it installs Vagrant version 1.9.7 rather than the one I've specified and none of the vagrant plugins are installed.  I can only get the settings above to work if I set them in a JSON file (and use a -j flag) when running chef solo.  I'm not an expert on Chef so I'm not sure if I'm doing something wrong in my wrapper cookbook or if the Vagrant cookbook has been written in such a way that I can't do this.

Here's the output from running Chef solo with my wrapper cookbook (using a Vagrant VM)

```
==> default: - ohai (5.2.0)
==> default: Installing Cookbook Gems:
==> default: Compiling Cookbooks...
==> default: Converging 2 resources
==> default: Recipe: vagrant::debian
==> default:   
==> default: * remote_file[/var/chef/cache/vagrant.deb] action create
==> default: [2017-11-20T16:24:32+00:00] INFO: remote_file[/var/chef/cache/vagrant.deb] created file /var/chef/cache/vagrant.deb
==> default:     
==> default: - create new file /var/chef/cache/vagrant.deb
==> default: [2017-11-20T16:24:32+00:00] INFO: remote_file[/var/chef/cache/vagrant.deb] updated file contents /var/chef/cache/vagrant.deb
==> default:     
==> default: - update content in file /var/chef/cache/vagrant.deb from none to d55798
==> default:     
==> default: (file sizes exceed 10000000 bytes, diff output suppressed)
==> default: 
==> default: 
==> default: [2017-11-20T16:24:33+00:00] INFO: remote_file[/var/chef/cache/vagrant.deb] sending install action to dpkg_package[vagrant] (immediate)
==> default:   
==> default: * dpkg_package[vagrant] action install
==> default: [2017-11-20T16:24:33+00:00] INFO: dpkg_package[vagrant] installing package(s): vagrant
==> default: [2017-11-20T16:24:36+00:00] INFO: dpkg_package[vagrant] installed vagrant at 1.9.7
==> default: 
==> default:     - install version 1.9.7 of package vagrant
==> default:   * dpkg_package[vagrant] action install
==> default: [2017-11-20T16:24:36+00:00] INFO: dpkg_package[vagrant] installing package(s): vagrant
==> default: [2017-11-20T16:24:40+00:00] INFO: dpkg_package[vagrant] installed vagrant at 1.9.7
==> default: 
==> default:     - install version 1.9.7 of package vagrant
==> default: 
==> default: [2017-11-20T16:24:40+00:00] INFO: Chef Run complete in 22.944263477 seconds
==> default: 
==> default: Running handlers:
==> default: [2017-11-20T16:24:40+00:00] INFO: Running report handlers
==> default: Running handlers complete
==> default: 
==> default: [2017-11-20T16:24:40+00:00] INFO: Report handlers complete
==> default: Chef Client finished, 3/3 resources updated in 24 seconds
```

Can you advise If I'm doing something wrong or if this is a bug.
Thanks.
Rich.

**Comment by MarkGibbons** [comment]
@rich-murray 

Does your wrapper cookbook have a "depends vagrant" in metadata? I did an override and installed 2.0.2 from a wrapper with no problems.

Mark

**Comment by rich-murray** [comment]
Yes I've got "depends vagrant" in metadata.rb.  I can't seem to re-produce the issue now as the version of vagrant I have specified is being installed.  I'm still getting an issue installing any vagrant plugins using a wrapper cookbook though (none of them are installed) . I'll close this for now and may raise a separate issue for the installation of plugins from a wrapper cookbook.
